version: '3.8'

services:
  db:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: airontools
    volumes:
      - ./mongo:/data/db
