name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Configura la rama que activará el workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/airontools-admin-api:latest

      - name: Run Docker Containers
        run: |
          docker run -d \
            --name airontools-admin-api \
            --env PORT=${{ secrets.PORT }} \
            --env SERVER_PORT=${{ secrets.SERVER_PORT }} \
            --env DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            --env DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            --env DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            --env DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
            --env HOST_API=${{ secrets.HOST_API }} \
            --env CLIENT_PORT=${{ secrets.CLIENT_PORT }} \
            --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --env AWS_REGION=${{ secrets.AWS_REGION }} \
            --env AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/airontools-admin-api:latest
